apiVersion: v1
kind: Service
metadata:
  name: aeron-cluster
  namespace: aeron-demo
spec:
  clusterIP: None
  selector:
    app: aeron-cluster
  ports:
    - name: placeholder
      port: 9000
      protocol: UDP
